# Generated by Django 2.0 on 2018-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180516_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodolist',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
