# Generated by Django 2.0 on 2018-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projecttodolist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltodoitem',
            name='project_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
