# Generated by Django 2.0 on 2018-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_personaltodoitem_project_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='added_to_master',
            field=models.BooleanField(default=False),
        ),
    ]
