# Generated by Django 2.0 on 2018-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_projecttodoitem_added_to_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
