# Generated by Django 2.0 on 2018-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevent',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
