# Generated by Django 2.0 on 2018-10-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_profile_active_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_knowledge',
            new_name='first_note',
        ),
    ]
