# Generated by Django 2.0 on 2018-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20181016_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_note_template',
            field=models.BooleanField(default=True),
        ),
    ]
