# Generated by Django 2.0 on 2018-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_projectpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_journal_template',
            field=models.BooleanField(default=True),
        ),
    ]
