# Generated by Django 2.0 on 2018-11-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_profile_beta_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
