# Generated by Django 2.0 on 2018-11-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20181127_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='base.Project'),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_tags', to='base.Profile'),
        ),
    ]
