# Generated by Django 2.0 on 2018-11-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20181127_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('name', 'project')},
        ),
    ]
