# Generated by Django 2.0 on 2018-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20181127_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
