# Generated by Django 2.0 on 2018-12-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20181127_2016'),
    ]

    operations = [

        migrations.AddField(
            model_name='profile',
            name='utc_offset',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='evening_reminder',
            field=models.CharField(default='21:00', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='midday_reminder',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='morning_reminder',
            field=models.CharField(default='07:00', max_length=20),
        ),
    ]
