# Generated by Django 2.0 on 2018-12-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_profile_utc_offset_and_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_answer', models.CharField(max_length=100)),
                ('how_startanswer', models.CharField(max_length=100)),
                ('blocker_answer', models.CharField(max_length=100)),
                ('review_answer', models.CharField(max_length=200)),
                ('success', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCycleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycles_num', models.IntegerField()),
                ('work_duration', models.CharField(max_length=10)),
                ('break_duration', models.CharField(max_length=10)),
                ('question_what', models.CharField(max_length=300)),
                ('question_how', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_groups', to='base.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='workcycle',
            name='cycle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='base.WorkCycleGroup'),
        ),
    ]
