# Generated by Django 2.0 on 2018-12-26 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20181226_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcyclegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
