# Generated by Django 2.0 on 2018-12-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_workcyclegroup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcycle',
            name='success',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='morning_reminder',
            field=models.CharField(default='', max_length=20),
        ),
    ]
