# Generated by Django 2.0 on 2019-01-11 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_projectresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpage',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
