# Generated by Django 2.0 on 2019-01-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20190111_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='extension',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
