# Generated by Django 2.0 on 2019-01-16 06:34

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_profile_total_upload_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='the_file',
            field=models.FileField(upload_to=apps.base.models.update_filename),
        ),
    ]
