# Generated by Django 2.0 on 2019-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20190122_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpageimage',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
