# Generated by Django 2.0 on 2019-01-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_projectpageimage_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodoitem',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='todos', to='base.ProjectTodoList'),
        ),
        migrations.RenameField(
            model_name='projecttodoitem',
            old_name='todo_list',
            new_name='project_list',
        ),
        migrations.AddField(
            model_name='personaltodoitem',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projecttodoitem',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projecttodoitem',
            name='personal_list',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_todos', to='base.PersonalTodoList'),
        ),
        migrations.AlterField(
            model_name='personaltodoitem',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projecttodoitem',
            name='title',
            field=models.CharField(max_length=300),
        )
    ]
