# Generated by Django 2.0 on 2019-01-26 18:24

from django.db import migrations



def forwards_func(apps, schema_editor):
    PersonalTodoItem = apps.get_model('base', 'PersonalTodoItem')
    ProjectTodoItem = apps.get_model('base', 'ProjectTodoItem')
    for personal_item in PersonalTodoItem.objects.all():
        if personal_item.project_item_id:
            try:
                project_item = ProjectTodoItem.objects.get(pk=personal_item.project_item_id)
                project_item.personal_list = personal_item.todo_list
                project_item.save()
            except Exception:
                print("Project item does not exist")
        else:
#            personal item that doesn't have project
            project_item = ProjectTodoItem(
                title=personal_item.title,
                completed=personal_item.completed,
                completed_on=personal_item.completed_on,
                personal_list_id=personal_item.todo_list_id,
                added_to_master=True,
                project_list=None
            )
            project_item.save()


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('base', '0046_auto_20190126_1824'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, atomic=False)
    ]

