# Generated by Django 2.0 on 2019-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20190129_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='personal_list_order',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projecttodoitem',
            name='project_list_order',
            field=models.FloatField(null=True),
        ),
    ]
