# Generated by Django 2.0 on 2019-01-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        ProjectTodoList = apps.get_model('base', 'ProjectTodoList')
        PersonalTodoList = apps.get_model('base', 'PersonalTodoList')
        for project_list in ProjectTodoList.objects.all():
            i = 1
            for todo_item in project_list.todos.order_by('id'):
                todo_item.project_list_order = i
                todo_item.save()
                i+=1
        for personal_list in PersonalTodoList.objects.all():
            i = 1
            for todo_item in personal_list.personal_todos.order_by('id'):
                todo_item.personal_list_order = i
                todo_item.save()
                i+=1

    def reverse_func(apps, schema_editor):
        ProjectTodoItem = apps.get_model('base', 'ProjectTodoItem')
        for project_item in ProjectTodoItem.objects.all():
            project_item.personal_list_order = None
            project_item.project_list_order = None
            project_item.save()

    dependencies = [
        ('base', '0051_create_new_order_fields'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, atomic=False)
    ]
