# Generated by Django 2.0 on 2019-02-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_fill_new_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcyclegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_groups', to='base.Project'),
        ),
    ]
