# Generated by Django 2.0 on 2019-02-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_workcyclegroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcyclegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_groups', to='base.Project'),
        ),
    ]
