# Generated by Django 2.0 on 2019-02-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20190208_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttodoitem',
            name='personal_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_todos', to='base.PersonalTodoList'),
        ),
        migrations.AlterField(
            model_name='projecttodoitem',
            name='project_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='base.ProjectTodoList'),
        ),
    ]
