# Generated by Django 2.0 on 2019-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20190208_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_work_stats',
            field=models.BooleanField(default=True),
        ),
    ]
