# Generated by Django 2.0 on 2019-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20190209_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passive',
            field=models.BooleanField(default=False),
        ),
    ]
