# Generated by Django 2.0 on 2019-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_profile_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancel_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cancellation_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_last_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(default='my-trial', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
