# Generated by Django 2.0 on 2019-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20190212_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_last_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
