# Generated by Django 2.0 on 2019-02-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20190212_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('event_subtype', models.CharField(max_length=30)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_plan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=20, null=True)),
                ('next_bill_date', models.DateField(blank=True, null=True)),
                ('cancellation_effective_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='base.Profile')),
            ],
        ),
    ]
