# Generated by Django 2.0 on 2019-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20190214_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcycle',
            name='energy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workcycle',
            name='success',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
