# Generated by Django 2.0 on 2019-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20190217_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcycle',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
