# Generated by Django 2.0 on 2019-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_workcycle_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cancel_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
