# Generated by Django 2.0 on 2019-03-22 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20190309_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardEvents',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('journal', models.CharField(blank=True, max_length=20, null=True)),
                ('journal_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=20, null=True)),
                ('project_date', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_date', models.DateTimeField(blank=True, null=True)),
                ('work', models.CharField(blank=True, max_length=20, null=True)),
                ('work_date', models.DateTimeField(blank=True, null=True)),
                ('habits', models.CharField(blank=True, max_length=20, null=True)),
                ('habits_date', models.DateTimeField(blank=True, null=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('onboard_canceled', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_events', to='base.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
