# Generated by Django 2.0 on 2019-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_onboardevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardevents',
            name='onboard_finished',
            field=models.BooleanField(default=False),
        ),
    ]
