# Generated by Django 2.0 on 2019-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20190404_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
