# Generated by Django 2.0 on 2019-05-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_projecttodoitem_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='day_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_todos', to='base.PersonalTodoList'),
        ),
    ]
