# Generated by Django 2.0 on 2019-05-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20190509_1548'),
        ('base', '0074_projecttodoitem_day_list'),
    ]

    operations = [
    ]
