# Generated by Django 2.0 on 2019-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20190519_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_week_plan',
            field=models.BooleanField(default=True),
        ),
    ]
