# Generated by Django 2.1.5 on 2019-06-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_profile_first_week_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='seconds_worked_today',
            field=models.IntegerField(default=0),
        ),
    ]
