# Generated by Django 2.1.5 on 2019-07-14 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20190706_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
