# Generated by Django 2.1.5 on 2019-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_projecttodoitem_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcyclegroup',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
