# Generated by Django 2.1.5 on 2019-08-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20190728_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTodoItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_todo_states', to='base.Project')),
            ],
        ),
    ]
