# Generated by Django 2.1.5 on 2019-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20190923_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
