# Generated by Django 2.1.5 on 2019-09-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_projecttodoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttodoitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_todos', to='base.Profile'),
        ),
    ]
