# Generated by Django 2.1.5 on 2019-10-15 05:59
import datetime

from django.db import migrations

from mastermind.utils import user_time_now


def calc_list_date(profile_utc_offset, list_name):
    DAY_MAP = {
        "Monday": 1,
        "Tuesday": 2,
        "Wednesday": 3,
        "Thursday": 4,
        "Friday": 5,
        "Saturday": 6,
        "Sunday": 7
    }
    users_today = user_time_now(profile_utc_offset).date()
    today_weekday = users_today.isoweekday()

    day_list_weekday = DAY_MAP[list_name]
    list_offset = day_list_weekday - today_weekday
    list_date = users_today + datetime.timedelta(days=list_offset)
    return list_date

def day_list_to_due_date(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PersonalTodoList = apps.get_model('base', 'PersonalTodoList')
    DAY_LIST_PRIORITY = 7
    count_lists = 0
    count_tasks = 0
    for dayList in PersonalTodoList.objects.filter(priority=DAY_LIST_PRIORITY):
        if dayList.day_todos:
            count_lists += 1
            list_date = calc_list_date(dayList.user.utc_offset, dayList.title)
            for todo_item in dayList.day_todos.all():
                if not todo_item.due_date:
                    todo_item.due_date = list_date
                    todo_item.save()
                    count_tasks += 1
    print("Processed {} lists".format(count_lists, count_tasks))

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20191015_0519'),
    ]

    operations = [
        migrations.RunPython(day_list_to_due_date),
    ]
