# Generated by Django 2.0 on 2018-05-15 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.BooleanField(default=True)),
                ('week', models.BooleanField(default=True)),
                ('month', models.BooleanField(default=True)),
                ('quarter', models.BooleanField(default=False)),
                ('year', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('entry_type', models.CharField(max_length=20)),
                ('created_on', models.DateField(default=datetime.datetime.utcnow)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('0', 'day'), ('1', 'week'), ('2', 'month'), ('3', 'quarter'), ('4', 'year')], max_length=20)),
                ('content', models.TextField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='journal.Journal')),
            ],
        ),
    ]
