# Generated by Django 2.0 on 2019-01-29 06:19

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20180910_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
