# Generated by Django 2.0 on 2019-01-29 06:36

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20190129_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltemplate',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
