# Generated by Django 2.0 on 2019-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20190129_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
