# Generated by Django 2.0 on 2019-02-24 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalentry_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
