# Generated by Django 2.0 on 2019-02-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20190224_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.BooleanField(default=True),
        ),
    ]
