# Generated by Django 2.0 on 2019-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitss', '0002_auto_20190130_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='schedule',
            field=models.CharField(default='1111111', max_length=10),
        ),
    ]
