# Generated by Django 2.0 on 2018-08-08 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
