# Generated by Django 2.0 on 2018-09-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_auto_20180808_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='note_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
