# Generated by Django 2.0 on 2018-09-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_noteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notebooks.Note'),
            preserve_default=False,
        ),
    ]
