# Generated by Django 2.0 on 2018-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_noteimage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNoteTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
