# Generated by Django 2.1.5 on 2019-10-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20191015_0559'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_date', models.DateField()),
                ('task_points', models.FloatField()),
                ('habit_points', models.FloatField()),
                ('journal_points', models.FloatField()),
                ('total_points', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_karma_points', to='base.Profile')),
            ],
        ),
    ]
